export const homeData = [
  {
    id: 1,
    name: "Light House",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: require("../src/pic/image/harr.jpg"),
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "skull island",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: require("../src/pic/image/eb5a893a8168846b4c41b2f319b66b28.png"),
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Pirates Sea",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: require("../src/pic/image/qq.png"),
    video: "../video/video3.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Sand Dust",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: require("../src/pic/image/dcdcec5bcb48c213877dd5bd388c142e.png"),
    video: "../video/video4.mp4",
    date: "12-Aug-2015",
  },
];

export const upcome = [
  {
    id: 1,
    cover: require("./pic/image/blackpantherwakandaforever_lob_crd_05.jpg"),
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: require("./pic/image/doctorstrangeinthemultiverseofmadness_lob_crd_02_3.jpg"),
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: require("./pic/image/logan_lob_crd_02.jpg"),
    name: "Logan",
    time: "2hr : 38mins",
  },
  {
    id: 4,

    cover: require("./pic/image/antmanandthewaspquantumania_lob_crd_02.jpg"),
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: require("./pic/image/eternals_lob_crd_06.jpg"),
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
];

export const latest = [
  {
    id: 1,
    cover: require("../src/pic/image/thorthedarkworld_lob_crd_02_1.jpg"),
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: require("../src/pic/image/thorloveandthunder_lob_crd_04.jpg"),
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: require("../src/pic/image/f7e1e12c242151c9a002518bb34fd4df.jpg"),
    name: "SEE",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: require("../src/pic/image/c9d9118099b6b899f62ba3ffa82903ee.jpg"),
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: require("../src/pic/image/99f8702093bd74454c4636a33f558c4a.jpg"),
    name: "Joker",
    time: "2hr : 38mins",
  },
];

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: require("../src/pic/image/aa309ebc851d6198a89540aae4c65306.jpg"),
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: require("../src/pic/image/89fbc84f94da740f6829c4e760a9309d.jpg"),
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: require("../src/pic/image/22e7d8bc70ebec5fbab2d75f6c13dc44.jpg"),
    date: "20-FEB-2010",
  },
];

export const recommended = [
  {
    id: 4,
    cover: require("../src/pic/image/3a07ac853ce63fb3328d1ca22d0922af.jpg"),
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: require("../src/pic/image/5b5f67cdabc31183072d27fb302a776e.jpg"),
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: require("../src/pic/image/e769bad83a56c4d8ccc406a821259478.jpg"),
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: require("../src/pic/image/e241b0dfcb84007a100630ad3dcbcb21.jpg"),
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: require("../src/pic/image/111c5c9ad99661af2d80e38948cf29d8.jpg"),
    name: "Another Danger",
    time: "2hr : 38mins",
  },
];
